<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit389393c90e26282960c95ba4200274b1
{
    public static $files = array (
        '65fec9ebcfbb3cbb4fd0d519687aea01' => __DIR__ . '/..' . '/danielstjules/stringy/src/Create.php',
        '72579e7bd17821bb1321b87411366eae' => __DIR__ . '/..' . '/illuminate/support/helpers.php',
        'e40631d46120a9c38ea139981f8dab26' => __DIR__ . '/..' . '/ircmaxell/password-compat/lib/password.php',
        'be9afea502afbd11e8ddf5f553601226' => __DIR__ . '/..' . '/rossriley/validation/autoload.php',
        'c964ee0ededf28c96ebd9db5099ef910' => __DIR__ . '/..' . '/guzzlehttp/promises/src/functions_include.php',
        'a0edc8309cc5e1d60e3047b5df6b7052' => __DIR__ . '/..' . '/guzzlehttp/psr7/src/functions_include.php',
        '9f7f3f9b1f82484e76bcd07b985a2d2f' => __DIR__ . '/..' . '/symfony/var-dumper/Symfony/Component/VarDumper/Resources/functions/dump.php',
        '0e2a1509d856a73a3968778840cb1de9' => __DIR__ . '/..' . '/rossriley/upload/autoload.php',
        '37a3dc5111fe8f707ab4c132ef1dbc62' => __DIR__ . '/..' . '/guzzlehttp/guzzle/src/functions_include.php',
        'f084d01b0a599f67676cffef638aa95b' => __DIR__ . '/..' . '/smarty/smarty/libs/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Component\\Translation\\' => 30,
            'Symfony\\Component\\Process\\' => 26,
            'Stringy\\' => 8,
        ),
        'P' => 
        array (
            'Psr\\Http\\Message\\' => 17,
        ),
        'N' => 
        array (
            'Nicolaslopezj\\Searchable\\' => 25,
        ),
        'L' => 
        array (
            'League\\Flysystem\\' => 17,
            'Lanz\\Commentable\\' => 17,
        ),
        'I' => 
        array (
            'Illuminate\\Support\\' => 19,
            'Illuminate\\Filesystem\\' => 22,
            'Illuminate\\Events\\' => 18,
            'Illuminate\\Database\\' => 20,
            'Illuminate\\Contracts\\' => 21,
            'Illuminate\\Container\\' => 21,
            'Illuminate\\Console\\' => 19,
            'Illuminate\\Config\\' => 18,
        ),
        'G' => 
        array (
            'GuzzleHttp\\Psr7\\' => 16,
            'GuzzleHttp\\Promise\\' => 19,
            'GuzzleHttp\\' => 11,
        ),
        'D' => 
        array (
            'Doctrine\\Common\\Cache\\' => 22,
        ),
        'C' => 
        array (
            'Cviebrock\\EloquentTaggable\\' => 27,
            'Cviebrock\\EloquentSluggable\\' => 28,
            'Cron\\' => 5,
            'Cocur\\Slugify\\' => 14,
            'Cartalyst\\Support\\' => 18,
            'Cartalyst\\Sentinel\\' => 19,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Component\\Translation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/translation',
        ),
        'Symfony\\Component\\Process\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/process',
        ),
        'Stringy\\' => 
        array (
            0 => __DIR__ . '/..' . '/danielstjules/stringy/src',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Nicolaslopezj\\Searchable\\' => 
        array (
            0 => __DIR__ . '/..' . '/nicolaslopezj/searchable/src',
        ),
        'League\\Flysystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/flysystem/src',
        ),
        'Lanz\\Commentable\\' => 
        array (
            0 => __DIR__ . '/..' . '/lanz/laravel-commentable/src/Commentable',
        ),
        'Illuminate\\Support\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/support',
        ),
        'Illuminate\\Filesystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/filesystem',
        ),
        'Illuminate\\Events\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/events',
        ),
        'Illuminate\\Database\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/database',
        ),
        'Illuminate\\Contracts\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/contracts',
        ),
        'Illuminate\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/container',
        ),
        'Illuminate\\Console\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/console',
        ),
        'Illuminate\\Config\\' => 
        array (
            0 => __DIR__ . '/..' . '/illuminate/config',
        ),
        'GuzzleHttp\\Psr7\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/psr7/src',
        ),
        'GuzzleHttp\\Promise\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/promises/src',
        ),
        'GuzzleHttp\\' => 
        array (
            0 => __DIR__ . '/..' . '/guzzlehttp/guzzle/src',
        ),
        'Doctrine\\Common\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/cache/lib/Doctrine/Common/Cache',
        ),
        'Cviebrock\\EloquentTaggable\\' => 
        array (
            0 => __DIR__ . '/..' . '/cviebrock/eloquent-taggable/src',
        ),
        'Cviebrock\\EloquentSluggable\\' => 
        array (
            0 => __DIR__ . '/..' . '/cviebrock/eloquent-sluggable/src',
        ),
        'Cron\\' => 
        array (
            0 => __DIR__ . '/..' . '/cron/cron/src',
        ),
        'Cocur\\Slugify\\' => 
        array (
            0 => __DIR__ . '/..' . '/cocur/slugify/src',
        ),
        'Cartalyst\\Support\\' => 
        array (
            0 => __DIR__ . '/..' . '/cartalyst/support/src',
        ),
        'Cartalyst\\Sentinel\\' => 
        array (
            0 => __DIR__ . '/..' . '/cartalyst/sentinel/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'o' => 
        array (
            'org\\bovigo\\vfs' => 
            array (
                0 => __DIR__ . '/..' . '/mikey179/vfsStream/src/main/php',
            ),
        ),
        'S' => 
        array (
            'Symfony\\Component\\VarDumper\\' => 
            array (
                0 => __DIR__ . '/..' . '/symfony/var-dumper',
            ),
            'Symfony\\Component\\Finder\\' => 
            array (
                0 => __DIR__ . '/..' . '/symfony/finder',
            ),
            'Symfony\\Component\\Debug\\' => 
            array (
                0 => __DIR__ . '/..' . '/symfony/debug',
            ),
            'Symfony\\Component\\Console\\' => 
            array (
                0 => __DIR__ . '/..' . '/symfony/console',
            ),
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 
            array (
                0 => __DIR__ . '/..' . '/psr/log',
            ),
            'Presenter' => 
            array (
                0 => __DIR__ . '/..' . '/jamierumbelow/presenters/libraries',
            ),
        ),
        'M' => 
        array (
            'Miladr\\Jalali' => 
            array (
                0 => __DIR__ . '/..' . '/miladr/jalali/src',
            ),
            'MarkWilson' => 
            array (
                0 => __DIR__ . '/..' . '/markwilson/xml-to-json/src',
            ),
        ),
        'D' => 
        array (
            'Doctrine\\DBAL\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/dbal/lib',
            ),
            'Doctrine\\Common\\Lexer\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/lexer/lib',
            ),
            'Doctrine\\Common\\Inflector\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/inflector/lib',
            ),
            'Doctrine\\Common\\Collections\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/collections/lib',
            ),
            'Doctrine\\Common\\Annotations\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/annotations/lib',
            ),
            'Doctrine\\Common\\' => 
            array (
                0 => __DIR__ . '/..' . '/doctrine/common/lib',
            ),
        ),
        'C' => 
        array (
            'Carbon' => 
            array (
                0 => __DIR__ . '/..' . '/nesbot/carbon/src',
            ),
        ),
        'B' => 
        array (
            'Baum' => 
            array (
                0 => __DIR__ . '/..' . '/baum/baum/src',
            ),
        ),
    );

    public static $classMap = array (
        'Eventviva\\ImageResize' => __DIR__ . '/..' . '/eventviva/php-image-resize/src/ImageResize.php',
        'Lanz\\Commentable\\MigrationCommand' => __DIR__ . '/..' . '/lanz/laravel-commentable/src/commands/MigrationCommand.php',
        'ezcArchive' => __DIR__ . '/..' . '/zetacomponents/archive/src/archive.php',
        'ezcArchiveBlockFile' => __DIR__ . '/..' . '/zetacomponents/archive/src/file/block_file.php',
        'ezcArchiveBlockSizeException' => __DIR__ . '/..' . '/zetacomponents/archive/src/exceptions/block_size.php',
        'ezcArchiveCallback' => __DIR__ . '/..' . '/zetacomponents/archive/src/interfaces/callback.php',
        'ezcArchiveCentralDirectoryEndHeader' => __DIR__ . '/..' . '/zetacomponents/archive/src/zip/headers/central_directory_end.php',
        'ezcArchiveCentralDirectoryHeader' => __DIR__ . '/..' . '/zetacomponents/archive/src/zip/headers/central_directory.php',
        'ezcArchiveCharacterFile' => __DIR__ . '/..' . '/zetacomponents/archive/src/file/character_file.php',
        'ezcArchiveChecksumException' => __DIR__ . '/..' . '/zetacomponents/archive/src/exceptions/checksum.php',
        'ezcArchiveChecksums' => __DIR__ . '/..' . '/zetacomponents/archive/src/utils/checksums.php',
        'ezcArchiveEmptyException' => __DIR__ . '/..' . '/zetacomponents/archive/src/exceptions/empty.php',
        'ezcArchiveEntry' => __DIR__ . '/..' . '/zetacomponents/archive/src/entry.php',
        'ezcArchiveEntryPrefixException' => __DIR__ . '/..' . '/zetacomponents/archive/src/exceptions/entry_prefix.php',
        'ezcArchiveException' => __DIR__ . '/..' . '/zetacomponents/archive/src/exceptions/exception.php',
        'ezcArchiveFile' => __DIR__ . '/..' . '/zetacomponents/archive/src/file/file.php',
        'ezcArchiveFileStructure' => __DIR__ . '/..' . '/zetacomponents/archive/src/structs/file.php',
        'ezcArchiveFileType' => __DIR__ . '/..' . '/zetacomponents/archive/src/utils/file_type.php',
        'ezcArchiveGnuHeader' => __DIR__ . '/..' . '/zetacomponents/archive/src/tar/headers/gnu.php',
        'ezcArchiveGnuTar' => __DIR__ . '/..' . '/zetacomponents/archive/src/tar/gnu.php',
        'ezcArchiveInternalException' => __DIR__ . '/..' . '/zetacomponents/archive/src/exceptions/internal_exception.php',
        'ezcArchiveIoException' => __DIR__ . '/..' . '/zetacomponents/archive/src/exceptions/io.php',
        'ezcArchiveLocalFileHeader' => __DIR__ . '/..' . '/zetacomponents/archive/src/zip/headers/local_file.php',
        'ezcArchiveOptions' => __DIR__ . '/..' . '/zetacomponents/archive/src/options/archive.php',
        'ezcArchivePaxHeader' => __DIR__ . '/..' . '/zetacomponents/archive/src/tar/headers/pax.php',
        'ezcArchivePaxTar' => __DIR__ . '/..' . '/zetacomponents/archive/src/tar/pax.php',
        'ezcArchiveStatMode' => __DIR__ . '/..' . '/zetacomponents/archive/src/utils/stat_mode.php',
        'ezcArchiveUnknownTypeException' => __DIR__ . '/..' . '/zetacomponents/archive/src/exceptions/unknown_type.php',
        'ezcArchiveUstarHeader' => __DIR__ . '/..' . '/zetacomponents/archive/src/tar/headers/ustar.php',
        'ezcArchiveUstarTar' => __DIR__ . '/..' . '/zetacomponents/archive/src/tar/ustar.php',
        'ezcArchiveV7Header' => __DIR__ . '/..' . '/zetacomponents/archive/src/tar/headers/v7.php',
        'ezcArchiveV7Tar' => __DIR__ . '/..' . '/zetacomponents/archive/src/tar/v7.php',
        'ezcArchiveValueException' => __DIR__ . '/..' . '/zetacomponents/archive/src/exceptions/value.php',
        'ezcArchiveZip' => __DIR__ . '/..' . '/zetacomponents/archive/src/zip/zip.php',
        'ezcBase' => __DIR__ . '/..' . '/zetacomponents/base/src/base.php',
        'ezcBaseAutoloadException' => __DIR__ . '/..' . '/zetacomponents/base/src/exceptions/autoload.php',
        'ezcBaseAutoloadOptions' => __DIR__ . '/..' . '/zetacomponents/base/src/options/autoload.php',
        'ezcBaseConfigurationInitializer' => __DIR__ . '/..' . '/zetacomponents/base/src/interfaces/configuration_initializer.php',
        'ezcBaseDoubleClassRepositoryPrefixException' => __DIR__ . '/..' . '/zetacomponents/base/src/exceptions/double_class_repository_prefix.php',
        'ezcBaseException' => __DIR__ . '/..' . '/zetacomponents/base/src/exceptions/exception.php',
        'ezcBaseExportable' => __DIR__ . '/..' . '/zetacomponents/base/src/interfaces/exportable.php',
        'ezcBaseExtensionNotFoundException' => __DIR__ . '/..' . '/zetacomponents/base/src/exceptions/extension_not_found.php',
        'ezcBaseFeatures' => __DIR__ . '/..' . '/zetacomponents/base/src/features.php',
        'ezcBaseFile' => __DIR__ . '/..' . '/zetacomponents/base/src/file.php',
        'ezcBaseFileException' => __DIR__ . '/..' . '/zetacomponents/base/src/exceptions/file_exception.php',
        'ezcBaseFileFindContext' => __DIR__ . '/..' . '/zetacomponents/base/src/structs/file_find_context.php',
        'ezcBaseFileIoException' => __DIR__ . '/..' . '/zetacomponents/base/src/exceptions/file_io.php',
        'ezcBaseFileNotFoundException' => __DIR__ . '/..' . '/zetacomponents/base/src/exceptions/file_not_found.php',
        'ezcBaseFilePermissionException' => __DIR__ . '/..' . '/zetacomponents/base/src/exceptions/file_permission.php',
        'ezcBaseFunctionalityNotSupportedException' => __DIR__ . '/..' . '/zetacomponents/base/src/exceptions/functionality_not_supported.php',
        'ezcBaseInit' => __DIR__ . '/..' . '/zetacomponents/base/src/init.php',
        'ezcBaseInitCallbackConfiguredException' => __DIR__ . '/..' . '/zetacomponents/base/src/exceptions/init_callback_configured.php',
        'ezcBaseInitInvalidCallbackClassException' => __DIR__ . '/..' . '/zetacomponents/base/src/exceptions/invalid_callback_class.php',
        'ezcBaseInvalidParentClassException' => __DIR__ . '/..' . '/zetacomponents/base/src/exceptions/invalid_parent_class.php',
        'ezcBaseMetaData' => __DIR__ . '/..' . '/zetacomponents/base/src/metadata.php',
        'ezcBaseMetaDataPearReader' => __DIR__ . '/..' . '/zetacomponents/base/src/metadata/pear.php',
        'ezcBaseMetaDataTarballReader' => __DIR__ . '/..' . '/zetacomponents/base/src/metadata/tarball.php',
        'ezcBaseOptions' => __DIR__ . '/..' . '/zetacomponents/base/src/options.php',
        'ezcBasePersistable' => __DIR__ . '/..' . '/zetacomponents/base/src/interfaces/persistable.php',
        'ezcBasePropertyNotFoundException' => __DIR__ . '/..' . '/zetacomponents/base/src/exceptions/property_not_found.php',
        'ezcBasePropertyPermissionException' => __DIR__ . '/..' . '/zetacomponents/base/src/exceptions/property_permission.php',
        'ezcBaseRepositoryDirectory' => __DIR__ . '/..' . '/zetacomponents/base/src/structs/repository_directory.php',
        'ezcBaseSettingNotFoundException' => __DIR__ . '/..' . '/zetacomponents/base/src/exceptions/setting_not_found.php',
        'ezcBaseSettingValueException' => __DIR__ . '/..' . '/zetacomponents/base/src/exceptions/setting_value.php',
        'ezcBaseStruct' => __DIR__ . '/..' . '/zetacomponents/base/src/struct.php',
        'ezcBaseValueException' => __DIR__ . '/..' . '/zetacomponents/base/src/exceptions/value.php',
        'ezcBaseWhateverException' => __DIR__ . '/..' . '/zetacomponents/base/src/exceptions/whatever.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit389393c90e26282960c95ba4200274b1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit389393c90e26282960c95ba4200274b1::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit389393c90e26282960c95ba4200274b1::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit389393c90e26282960c95ba4200274b1::$classMap;

        }, null, ClassLoader::class);
    }
}
